name: megamart
version: '1.0'
config-version: 2

profile: megamart

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  megamart:
    region_area_mapping:
      +column_types:
        region: string
        area: string
