"""
Generation configuration.

Dataset sizes are controlled by the DATASET_SIZE environment variable.

Available modes:

    local
        Small dataset for local development.

    ci
        Medium dataset used in GitHub Actions.

    full
        Large dataset used for performance testing.

Default:
    local
"""

import os

MODE = os.getenv("DATASET_SIZE", "local").lower()

if MODE == "local":

    NUM_CUSTOMERS = 50
    NUM_STORES = 5
    NUM_PRODUCTS = 80
    NUM_CAMPAIGNS = 20

    MIN_TREATMENT_SIZE = 2
    MIN_CONTROL_SIZE = 2

    NUM_BUNDLES = 20

    NUM_CLICKSTREAM_SESSIONS = 100
    NUM_TRANSACTIONS = 200

    LIMIT_COMPETITOR_PRODUCTS = 100
    LIMIT_COMPETITOR_PRICE_HISTORY = 2_000
    LIMIT_STORE_CATALOGUES = 320
    LIMIT_PRODUCT_LIFECYCLES = 240
    LIMIT_PRODUCT_CONTENT_QUALITY = 240
    LIMIT_STOCKOUT_EVENTS = 160
    LIMIT_STOCK_SNAPSHOTS = 250
    LIMIT_INVENTORY_CHANGE_EVENTS = 1_000
    LIMIT_CAMPAIGN_ASSIGNMENTS = 1_500
    LIMIT_CAMPAIGN_EXPOSURES = 4_500
    LIMIT_BUNDLE_PRICINGS = 60
    LIMIT_BUNDLE_ITEMS = 70
    LIMIT_PROMOTIONS = 80
    LIMIT_CLICKSTREAM_EVENTS = 2_000
    LIMIT_TRANSACTION_ITEMS = 1_800
    LIMIT_PRODUCT_REVIEWS = 200

elif MODE == "ci":

    NUM_CUSTOMERS = 500
    NUM_STORES = 20
    NUM_PRODUCTS = 300
    NUM_CAMPAIGNS = 100

    MIN_TREATMENT_SIZE = 20
    MIN_CONTROL_SIZE = 20

    NUM_BUNDLES = 80

    NUM_CLICKSTREAM_SESSIONS = 1_500
    NUM_TRANSACTIONS = 2_000

    LIMIT_COMPETITOR_PRODUCTS = 1_000
    LIMIT_COMPETITOR_PRICE_HISTORY = 15_000
    LIMIT_STORE_CATALOGUES = 3_000
    LIMIT_PRODUCT_LIFECYCLES = 1_500
    LIMIT_PRODUCT_CONTENT_QUALITY = 1_500
    LIMIT_STOCKOUT_EVENTS = 800
    LIMIT_STOCK_SNAPSHOTS = 1_000
    LIMIT_INVENTORY_CHANGE_EVENTS = 4_000
    LIMIT_CAMPAIGN_ASSIGNMENTS = 10_000
    LIMIT_CAMPAIGN_EXPOSURES = 20_000
    LIMIT_BUNDLE_PRICINGS = 200
    LIMIT_BUNDLE_ITEMS = 200
    LIMIT_PROMOTIONS = 500
    LIMIT_CLICKSTREAM_EVENTS = 20_000
    LIMIT_TRANSACTION_ITEMS = 10_000
    LIMIT_PRODUCT_REVIEWS = 2_000

elif MODE == "full":

    NUM_CUSTOMERS = 1_000
    NUM_STORES = 50
    NUM_PRODUCTS = 800
    NUM_CAMPAIGNS = 500

    MIN_TREATMENT_SIZE = 50
    MIN_CONTROL_SIZE = 50

    NUM_BUNDLES = 300

    NUM_CLICKSTREAM_SESSIONS = 5_000
    NUM_TRANSACTIONS = 8_000

    LIMIT_COMPETITOR_PRODUCTS = 5_000
    LIMIT_COMPETITOR_PRICE_HISTORY = 100_000
    LIMIT_STORE_CATALOGUES = 25_000
    LIMIT_PRODUCT_LIFECYCLES = 4_000
    LIMIT_PRODUCT_CONTENT_QUALITY = 4_000
    LIMIT_STOCKOUT_EVENTS = 2_500
    LIMIT_STOCK_SNAPSHOTS = 5_000
    LIMIT_INVENTORY_CHANGE_EVENTS = 10_000
    LIMIT_CAMPAIGN_ASSIGNMENTS = 50_000
    LIMIT_CAMPAIGN_EXPOSURES = 100_000
    LIMIT_BUNDLE_PRICINGS = 700
    LIMIT_BUNDLE_ITEMS = 500
    LIMIT_PROMOTIONS = 2_000
    LIMIT_CLICKSTREAM_EVENTS = 150_000
    LIMIT_TRANSACTION_ITEMS = 50_000
    LIMIT_PRODUCT_REVIEWS = 10_000

else:
    raise ValueError(
        f"Unknown DATASET_SIZE '{MODE}'. " "Choose one of: local, ci, full."
    )
