STORE_TYPE = {
    "Flagship": 0.08,
    "Mall": 0.4,
    "Neighbourhood": 0.52,
}


MALL_TO_AREA = {
    "Waterway Point": "Punggol",
    "Junction 8": "Bishan",
    "IMM": "Jurong East",
    "Northpoint": "Yishun",
    "Hougang Mall": "Hougang",
    "Causeway Point": "Woodlands",
    "NEX": "Serangoon",
    "VivoCity": "HarbourFront",
    "ION": "Orchard",
    "313@Somerset": "Somerset",
    "Bugis+": "Bugis",
    "The Seletar Mall": "Seletar",
    "Ang Mo Kio Hub": "Ang Mo Kio",
    "Sun Plaza": "Sembawang",
    "City Square Mall": "Farrer Park",
    "Westgate": "Jurong East",
    "JEM": "Jurong East",
    "Lot One": "Choa Chu Kang",
    "White Sands": "Pasir Ris",
    "Clarke Quay Central": "Clarke Quay",
    "Eastpoint Mall": "Pasir Ris",
    "Marina Square": "Marina Bay",
    "Raffles City": "Downtown Core",
    "Tampines Mall": "Tampines",
    "Great World City": "River Valley",
    "Plaza Singapura": "Dhoby Ghaut",
    "Orchard Central": "Orchard",
    "The Centrepoint": "Orchard",
    "Suntec City": "Marina Centre",
    "Funan Mall": "City Hall",
    "The Star Vista": "Buona Vista",
    "Bedok Mall": "Bedok",
    "Changi City Point": "Changi",
    "The Cathay": "Dhoby Ghaut",
    "Velocity": "Novena",
    "Kallang Wave Mall": "Kallang",
    "The Rail Mall": "Upper Bukit Timah",
    "The Clementi Mall": "Clementi",
    "Tanglin Mall": "Tanglin",
    "Millenia Walk": "Marina Bay",
    "West Coast Plaza": "West Coast",
    "Bukit Panjang Plaza": "Bukit Panjang",
    "Tiong Bahru Plaza": "Tiong Bahru",
    "Anchorpoint": "Alexandra",
    "The Woodleigh Mall": "Woodleigh",
    "Citylink Mall": "City Hall",
    "UE Square": "River Valley",
    "i12 Katong": "Marine Parade",
    "Marine Parade Central": "Marine Parade",
    "The Grandstand": "Bukit Timah",
    "Hillion Mall": "Bukit Panjang",
}
