megamart:
  target: dirty
  outputs:
    raw:
      type: bigquery
      method: oauth
      project: mega-mart-storage
      dataset: synthetic_raw
      threads: 1
      timeout_seconds: 300
      location: asia-southeast1

    dirty:
      type: bigquery
      method: oauth
      project: mega-mart-storage
      dataset: synthetic_dirty
      threads: 1
      timeout_seconds: 300
      location: asia-southeast1

    clean:
      type: bigquery
      method: oauth
      project: mega-mart-storage
      dataset: synthetic_clean
      threads: 1
      timeout_seconds: 300
      location: asia-southeast1
