DEPENDENCIES = {
    "customers_generator": [],
    "stores_generator": [],
    "products_generator": [],
    "competitor_products_generator": ["products_generator"],
    "store_catalogues_generator": ["stores_generator", "products_generator"],
    "product_lifecycles_generator": ["products_generator"],
    "product_content_quality_generator": [
        "products_generator",
        "product_lifecycles_generator",
    ],
    "stockout_events_generator": [
        "stores_generator",
        "products_generator",
        "store_catalogues_generator",
        "product_lifecycles_generator",
    ],
    "stock_snapshots_generator": [
        "stores_generator",
        "products_generator",
        "store_catalogues_generator",
        "product_lifecycles_generator",
        "stockout_events_generator",
    ],
    "campaigns_generator": [],
    "campaign_assignments_generator": ["customers_generator", "campaigns_generator"],
    "bundles_generator": ["products_generator"],
    "promotions_generator": [
        "products_generator",
        "product_lifecycles_generator",
        "campaigns_generator",
        "bundles_generator",
    ],
    "clickstreams_generator": [
        "customers_generator",
        "stores_generator",
        "products_generator",
        "stock_snapshots_generator",
        "campaigns_generator",
        "campaign_assignments_generator",
        "bundles_generator",
        "promotions_generator",
    ],
    "transactions_generator": [
        "customers_generator",
        "stores_generator",
        "products_generator",
        "store_catalogues_generator",
        "bundles_generator",
        "promotions_generator",
        "clickstreams_generator",
        "stock_snapshots_generator",
    ],
    "product_reviews_generator": ["products_generator", "transactions_generator"],
}
